---
- name: Create MariaDB database
  mysql_db:
    login_host: localhost
    name: wordpress
    state: present
- name: mysql_root_password
  vars:
    mysql_root_password: "Password"
  mysql_user:
    name: adminuser
    host: localhost
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
    update_password: always
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    login_host: localhost
    state: absent
- name: Removes the MySQL test database
  mysql_db: name=test state=absent login_password="" login_user=root
- name: Set up wp-config
  template:
    src: "files/wp-config.php.j2"
    dest: "/var/www/html/wp-config.php"
    owner: apache
    group: apache
    mode: '0755'